feat(player): add `hide` method to PlayerHelpPreferences and update persistence logic
- Introduce `hide` method for managing hidden help messages.
- Update PlayerDataManager init block to load all required classes to avoid NoClassDefFoundError

Signed-off-by: Fantamomo <git@fantamomo.com>